# Dependencies
markdown:         kramdown
highlighter:      rogue
pygments: 		  false

#Gems
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            devential
tagline:          'research and notes'
description:      'Cosolidating notes about my research, class work, and life.'
url:              http://devential.ml
baseurl:          '/'
paginate:         5
paginate_path:    "/blog/page:num"
paginateurl:    "/blog/"

author:
  name:           'devential'
  url:            https://twitter.com/devential

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/devential/devential.github.io
