# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:         true

#Gems
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            devblog
tagline:          'research and notes'
description:      'Cosolidating notes about my research, class work, and life.'
url:              http://devential.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'devential'
  url:            https://twitter.com/devential

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/devential/devential.github.io
